// =============================================================================
// generated_config.h — AUTO-GENERATED by inject_spec.py (layers format)
// Generated: 2026-03-22T09:59:30.147552+00:00
// Plugin:     TestMultiEffect
// DO NOT EDIT MANUALLY — changes will be overwritten on next build
// =============================================================================

#pragma once

#include <JuceHeader.h>

// ── Plugin Metadata ──────────────────────────────────────────────────────────
#define CHIBI_PLUGIN_NAME        "TestMultiEffect"
#define CHIBI_PLUGIN_TYPE        "EFFECT"
#define CHIBI_MANUFACTURER       "Chibitek Labs"
#define CHIBI_PLUGIN_DESCRIPTION "Reverb into delay combo"
#define CHIBI_VERSION_STRING     "1.0.0"
#define CHIBI_VERSION_HEX        0x010000
#define CHIBI_VERSION_MAJOR      1
#define CHIBI_VERSION_MINOR      0
#define CHIBI_VERSION_PATCH      0
#define CHIBI_NUM_PARAMETERS     6
#define NUM_LAYERS               2

// ── Layer 0: Reverb (reverb) ──────────────────────────
#define LAYER_0_ID          "reverb_0"
#define LAYER_0_TYPE        "reverb"
#define LAYER_0_LABEL       "Reverb"
#define LAYER_0_BLEND       1.000000f
#define LAYER_0_PARAM_COUNT 3

#define LAYER_0_PARAM_0_ID      "layer0_roomSize"
#define LAYER_0_PARAM_0_NAME    "Room Size"
#define LAYER_0_PARAM_0_MIN     0.000000f
#define LAYER_0_PARAM_0_MAX     1.000000f
#define LAYER_0_PARAM_0_DEFAULT 0.600000f
#define LAYER_0_PARAM_1_ID      "layer0_damping"
#define LAYER_0_PARAM_1_NAME    "Damping"
#define LAYER_0_PARAM_1_MIN     0.000000f
#define LAYER_0_PARAM_1_MAX     1.000000f
#define LAYER_0_PARAM_1_DEFAULT 0.400000f
#define LAYER_0_PARAM_2_ID      "layer0_mix"
#define LAYER_0_PARAM_2_NAME    "Mix"
#define LAYER_0_PARAM_2_MIN     0.000000f
#define LAYER_0_PARAM_2_MAX     1.000000f
#define LAYER_0_PARAM_2_DEFAULT 0.500000f

// ── Layer 1: Delay (delay) ──────────────────────────
#define LAYER_1_ID          "delay_0"
#define LAYER_1_TYPE        "delay"
#define LAYER_1_LABEL       "Delay"
#define LAYER_1_BLEND       0.800000f
#define LAYER_1_PARAM_COUNT 3

#define LAYER_1_PARAM_0_ID      "layer1_delayTime"
#define LAYER_1_PARAM_0_NAME    "Delay Time"
#define LAYER_1_PARAM_0_MIN     1.000000f
#define LAYER_1_PARAM_0_MAX     2000.000000f
#define LAYER_1_PARAM_0_DEFAULT 250.000000f
#define LAYER_1_PARAM_1_ID      "layer1_feedback"
#define LAYER_1_PARAM_1_NAME    "Feedback"
#define LAYER_1_PARAM_1_MIN     0.000000f
#define LAYER_1_PARAM_1_MAX     0.950000f
#define LAYER_1_PARAM_1_DEFAULT 0.300000f
#define LAYER_1_PARAM_2_ID      "layer1_mix"
#define LAYER_1_PARAM_2_NAME    "Mix"
#define LAYER_1_PARAM_2_MIN     0.000000f
#define LAYER_1_PARAM_2_MAX     1.000000f
#define LAYER_1_PARAM_2_DEFAULT 0.400000f

// ── Parameter Layout Helper ──────────────────────────────────────────────────
// Call createParameterLayout() and pass result to APVTS constructor.
inline juce::AudioProcessorValueTreeState::ParameterLayout createParameterLayout()
{
    juce::AudioProcessorValueTreeState::ParameterLayout layout;

    // Layer 0 (Reverb) — Room Size
    layout.add(std::make_unique<juce::AudioParameterFloat>(
        juce::ParameterID { "layer0_roomSize", 1 },
        "Room Size",
        juce::NormalisableRange<float>(0.000000f, 1.000000f, 0.000000f, 1.000000f),
        0.600000f,
        juce::String("")
    ));

    // Layer 0 (Reverb) — Damping
    layout.add(std::make_unique<juce::AudioParameterFloat>(
        juce::ParameterID { "layer0_damping", 1 },
        "Damping",
        juce::NormalisableRange<float>(0.000000f, 1.000000f, 0.000000f, 1.000000f),
        0.400000f,
        juce::String("")
    ));

    // Layer 0 (Reverb) — Mix
    layout.add(std::make_unique<juce::AudioParameterFloat>(
        juce::ParameterID { "layer0_mix", 1 },
        "Mix",
        juce::NormalisableRange<float>(0.000000f, 1.000000f, 0.000000f, 1.000000f),
        0.500000f,
        juce::String("%")
    ));

    // Layer 1 (Delay) — Delay Time
    layout.add(std::make_unique<juce::AudioParameterFloat>(
        juce::ParameterID { "layer1_delayTime", 1 },
        "Delay Time",
        juce::NormalisableRange<float>(1.000000f, 2000.000000f, 0.000000f, 1.000000f),
        250.000000f,
        juce::String(" ms")
    ));

    // Layer 1 (Delay) — Feedback
    layout.add(std::make_unique<juce::AudioParameterFloat>(
        juce::ParameterID { "layer1_feedback", 1 },
        "Feedback",
        juce::NormalisableRange<float>(0.000000f, 0.950000f, 0.000000f, 1.000000f),
        0.300000f,
        juce::String("")
    ));

    // Layer 1 (Delay) — Mix
    layout.add(std::make_unique<juce::AudioParameterFloat>(
        juce::ParameterID { "layer1_mix", 1 },
        "Mix",
        juce::NormalisableRange<float>(0.000000f, 1.000000f, 0.000000f, 1.000000f),
        0.400000f,
        juce::String("%")
    ));

    return layout;
}

// ── Plugin Type Flags ────────────────────────────────────────────────────────
#define CHIBI_IS_EFFECT      1
#define CHIBI_IS_INSTRUMENT  0
#define CHIBI_IS_ANALYZER    0

