#pragma once

#include <JuceHeader.h>
#include "generated_config.h"

//==============================================================================
/**
 * MultiEffectAudioProcessor
 *
 * Layered multi-effect chain. Supports up to 6 DSP layers:
 *   reverb, delay, eq, chorus, compressor, distortion
 *
 * Layer configuration is read from generated_config.h (auto-generated by
 * inject_spec.py).  Each layer is processed in order; blend controls wet/dry.
 */
class MultiEffectAudioProcessor : public juce::AudioProcessor
{
public:
    //==========================================================================
    MultiEffectAudioProcessor();
    ~MultiEffectAudioProcessor() override;

    //==========================================================================
    void prepareToPlay  (double sampleRate, int samplesPerBlock) override;
    void releaseResources() override;

    bool isBusesLayoutSupported (const BusesLayout& layouts) const override;

    void processBlock (juce::AudioBuffer<float>&, juce::MidiBuffer&) override;
    using AudioProcessor::processBlock;

    //==========================================================================
    juce::AudioProcessorEditor* createEditor() override;
    bool hasEditor() const override;

    //==========================================================================
    const juce::String getName() const override;
    bool  acceptsMidi()  const override;
    bool  producesMidi() const override;
    bool  isMidiEffect() const override;
    double getTailLengthSeconds() const override;

    //==========================================================================
    int  getNumPrograms()    override;
    int  getCurrentProgram() override;
    void setCurrentProgram (int index) override;
    const juce::String getProgramName (int index) override;
    void changeProgramName (int index, const juce::String& newName) override;

    //==========================================================================
    void getStateInformation (juce::MemoryBlock& destData) override;
    void setStateInformation (const void* data, int sizeInBytes) override;

    //==========================================================================
    // APVTS — exposed for editor bindings
    juce::AudioProcessorValueTreeState apvts;

    //==========================================================================
    // Layer config (public for editor access)
    static constexpr int kMaxLayers        = 6;
    static constexpr int kMaxParamsPerLayer = 8;

    struct LayerConfig
    {
        juce::String id;
        juce::String type;
        juce::String label;
        float  blend      = 1.0f;
        int    paramCount = 0;
        juce::String paramIds   [kMaxParamsPerLayer];
        juce::String paramNames [kMaxParamsPerLayer];
    };

    LayerConfig layerConfigs [kMaxLayers];
    int         numLayers = 0;

    // Raw parameter pointers [layer][param] — thread-safe atomic reads
    std::atomic<float>* layerParamPtrs [kMaxLayers][kMaxParamsPerLayer] = {};

private:
    //==========================================================================
    // DSP objects — one slot per layer (max kMaxLayers of each type)
    juce::dsp::Reverb reverbDsp [kMaxLayers];

    // Delay: simple ring-buffer per layer, per channel
    struct DelayState
    {
        std::array<std::vector<float>, 2> buf;
        std::array<int, 2> writePos { 0, 0 };
        void prepare (int maxSamples)
        {
            for (auto& b : buf) { b.assign (maxSamples, 0.0f); }
            writePos = { 0, 0 };
        }
    };
    DelayState delayState [kMaxLayers];

    // EQ: stereo IIR biquad
    using IIRFilter = juce::dsp::ProcessorDuplicator<
        juce::dsp::IIR::Filter<float>,
        juce::dsp::IIR::Coefficients<float>>;
    IIRFilter eqDsp [kMaxLayers];

    // Chorus
    juce::dsp::Chorus<float> chorusDsp [kMaxLayers];

    // Compressor
    juce::dsp::Compressor<float> compressorDsp [kMaxLayers];

    // Distortion (soft-clip waveshaper)
    juce::dsp::WaveShaper<float> distortionDsp [kMaxLayers];

    //==========================================================================
    double currentSampleRate = 44100.0;
    int    currentBlockSize  = 512;

    //==========================================================================
    void initLayerConfigs();
    void processLayer (int layerIdx, juce::AudioBuffer<float>& buffer);
    void processDelayLayer (int layerIdx, juce::AudioBuffer<float>& buffer,
                            int delaySamples, float feedback);

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MultiEffectAudioProcessor)
};
