#!/usr/bin/env python3
"""
inject_spec.py — DspSpec → generated_config.h injector

Takes a DspSpec JSON and a JUCE template directory.
Writes `generated_config.h` into the template's Source/ directory so the
JUCE PluginProcessor can include it for parameter defaults and plugin metadata.

Usage:
    python3 inject_spec.py \
        --spec '{"plugin_type":"effect","parameters":[...]}' \
        --template templates/MyTemplate \
        --plugin-name MyPlugin \
        [--dry-run]
"""

import argparse
import json
import os
import sys
import textwrap
from datetime import datetime, timezone
from pathlib import Path


# ── DspSpec schema ────────────────────────────────────────────────────────────
# Expected JSON shape:
# {
#   "plugin_type": "effect" | "instrument" | "analyzer",
#   "plugin_version": "1.0.0",           (optional)
#   "manufacturer": "Chibitek Labs",      (optional)
#   "description": "...",                 (optional)
#   "parameters": [
#     {
#       "id":      "gain",                 (required, C-safe identifier)
#       "name":    "Gain",                 (required, display name)
#       "min":     0.0,                    (required)
#       "max":     1.0,                    (required)
#       "default": 0.5,                    (required)
#       "unit":    "linear" | "dB" | "Hz" | "ms" | "%"  (optional)
#       "skew":    1.0,                    (optional, JUCE skew factor)
#       "step":    0.0,                    (optional, 0 = continuous)
#     }
#   ]
# }
# ─────────────────────────────────────────────────────────────────────────────


UNIT_SUFFIX_MAP = {
    "dB":     " dB",
    "Hz":     " Hz",
    "kHz":    " kHz",
    "ms":     " ms",
    "%":      "%",
    "linear": "",
    "":       "",
}


def sanitize_id(raw_id: str) -> str:
    """Make a safe C macro/variable identifier from a parameter id."""
    out = ""
    for ch in raw_id:
        if ch.isalnum() or ch == "_":
            out += ch.upper()
        else:
            out += "_"
    return out or "PARAM"


def validate_spec(spec: dict) -> list[str]:
    errors = []
    if "parameters" not in spec:
        errors.append("'parameters' array is required in DspSpec")
    else:
        for i, p in enumerate(spec["parameters"]):
            for field in ("id", "name", "min", "max", "default"):
                if field not in p:
                    errors.append(f"Parameter[{i}] missing required field '{field}'")
            if "id" in p and "default" in p:
                if not (p.get("min", 0) <= p["default"] <= p.get("max", 1)):
                    errors.append(
                        f"Parameter '{p['id']}' default {p['default']} is outside "
                        f"[{p.get('min')}, {p.get('max')}]"
                    )
    return errors


def render_header(spec: dict, plugin_name: str) -> str:
    params = spec.get("parameters", [])
    plugin_type = spec.get("plugin_type", "effect").upper()
    plugin_version = spec.get("plugin_version", "1.0.0")
    manufacturer = spec.get("manufacturer", "Chibitek Labs")
    description = spec.get("description", f"{plugin_name} — generated by Chibitek Platform")

    version_parts = plugin_version.split(".")
    version_major = int(version_parts[0]) if len(version_parts) > 0 else 1
    version_minor = int(version_parts[1]) if len(version_parts) > 1 else 0
    version_patch = int(version_parts[2]) if len(version_parts) > 2 else 0
    version_hex = (version_major << 16) | (version_minor << 8) | version_patch

    timestamp = datetime.now(timezone.utc).isoformat()

    lines = []
    lines.append("// =============================================================================")
    lines.append("// generated_config.h — AUTO-GENERATED by inject_spec.py")
    lines.append(f"// Generated: {timestamp}")
    lines.append(f"// Plugin:     {plugin_name}")
    lines.append(f"// DO NOT EDIT MANUALLY — changes will be overwritten on next build")
    lines.append("// =============================================================================")
    lines.append("")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <JuceHeader.h>")
    lines.append("")

    # ── Plugin metadata ──────────────────────────────────────────────────────
    lines.append("// ── Plugin Metadata ──────────────────────────────────────────────────────────")
    lines.append(f'#define CHIBI_PLUGIN_NAME        "{plugin_name}"')
    lines.append(f'#define CHIBI_PLUGIN_TYPE        "{plugin_type}"')
    lines.append(f'#define CHIBI_MANUFACTURER       "{manufacturer}"')
    lines.append(f'#define CHIBI_PLUGIN_DESCRIPTION "{description}"')
    lines.append(f'#define CHIBI_VERSION_STRING     "{plugin_version}"')
    lines.append(f"#define CHIBI_VERSION_HEX        0x{version_hex:06X}")
    lines.append(f"#define CHIBI_VERSION_MAJOR      {version_major}")
    lines.append(f"#define CHIBI_VERSION_MINOR      {version_minor}")
    lines.append(f"#define CHIBI_VERSION_PATCH      {version_patch}")
    lines.append(f"#define CHIBI_NUM_PARAMETERS     {len(params)}")
    lines.append("")

    # ── Parameter IDs (string constants) ────────────────────────────────────
    lines.append("// ── Parameter IDs ────────────────────────────────────────────────────────────")
    for p in params:
        safe = sanitize_id(p["id"])
        lines.append(f'#define PARAM_ID_{safe}  "{p["id"]}"')
    lines.append("")

    # ── Parameter defaults ───────────────────────────────────────────────────
    lines.append("// ── Parameter Defaults ───────────────────────────────────────────────────────")
    for p in params:
        safe = sanitize_id(p["id"])
        lines.append(f'#define PARAM_DEFAULT_{safe}  {float(p["default"]):.6f}f')
        lines.append(f'#define PARAM_MIN_{safe}       {float(p["min"]):.6f}f')
        lines.append(f'#define PARAM_MAX_{safe}       {float(p["max"]):.6f}f')
    lines.append("")

    # ── JUCE AudioProcessorValueTreeState parameter layout ───────────────────
    lines.append("// ── Parameter Layout Helper ──────────────────────────────────────────────────")
    lines.append("// Call createParameterLayout() and pass result to APVTS constructor.")
    lines.append("inline juce::AudioProcessorValueTreeState::ParameterLayout createParameterLayout()")
    lines.append("{")
    lines.append("    juce::AudioProcessorValueTreeState::ParameterLayout layout;")
    lines.append("")
    for p in params:
        pid = p["id"]
        safe = sanitize_id(pid)
        name = p["name"]
        pmin = float(p["min"])
        pmax = float(p["max"])
        pdef = float(p["default"])
        skew = float(p.get("skew", 1.0))
        step = float(p.get("step", 0.0))
        unit = UNIT_SUFFIX_MAP.get(p.get("unit", ""), "")

        lines.append(f'    // {name}')
        lines.append(f'    layout.add(std::make_unique<juce::AudioParameterFloat>(')
        lines.append(f'        juce::ParameterID {{ PARAM_ID_{safe}, 1 }},')
        lines.append(f'        "{name}",')
        lines.append(f'        juce::NormalisableRange<float>({pmin:.6f}f, {pmax:.6f}f, {step:.6f}f, {skew:.6f}f),')
        lines.append(f'        {pdef:.6f}f,')
        lines.append(f'        juce::String("{unit}")')
        lines.append(f'    ));')
        lines.append("")

    lines.append("    return layout;")
    lines.append("}")
    lines.append("")

    # ── Plugin type flags ────────────────────────────────────────────────────
    lines.append("// ── Plugin Type Flags ────────────────────────────────────────────────────────")
    pt = spec.get("plugin_type", "effect").lower()
    lines.append(f"#define CHIBI_IS_EFFECT      {'1' if pt == 'effect'     else '0'}")
    lines.append(f"#define CHIBI_IS_INSTRUMENT  {'1' if pt == 'instrument' else '0'}")
    lines.append(f"#define CHIBI_IS_ANALYZER    {'1' if pt == 'analyzer'   else '0'}")
    lines.append("")

    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Inject DspSpec into JUCE template")
    parser.add_argument("--spec",        required=True,  help="DspSpec JSON string or @file path")
    parser.add_argument("--template",    required=True,  help="Path to template directory")
    parser.add_argument("--plugin-name", required=True,  help="Plugin display name")
    parser.add_argument("--dry-run",     action="store_true", help="Validate only, don't write")
    args = parser.parse_args()

    # ── Load spec ─────────────────────────────────────────────────────────────
    spec_str = args.spec
    if spec_str.startswith("@"):
        spec_path = Path(spec_str[1:])
        if not spec_path.exists():
            print(f"ERROR: Spec file not found: {spec_path}", file=sys.stderr)
            sys.exit(1)
        spec_str = spec_path.read_text()

    try:
        spec = json.loads(spec_str)
    except json.JSONDecodeError as e:
        print(f"ERROR: Invalid DspSpec JSON: {e}", file=sys.stderr)
        sys.exit(1)

    # ── Normalize field aliases ───────────────────────────────────────────────
    # Accept "type" as an alias for "plugin_type" (common shorthand)
    if "type" in spec and "plugin_type" not in spec:
        spec["plugin_type"] = spec.pop("type")

    template_dir = Path(args.template)

    # ── Fall back to template's dsp_spec.json for missing parameters ──────────
    if "parameters" not in spec:
        fallback_path = template_dir / "dsp_spec.json"
        if fallback_path.exists():
            try:
                fallback = json.loads(fallback_path.read_text())
                if "parameters" in fallback:
                    print(f"INFO: 'parameters' not in input spec — merging from {fallback_path}", file=sys.stderr)
                    # Merge: input spec takes priority for everything except missing parameters
                    merged = {**fallback, **spec}
                    spec = merged
            except json.JSONDecodeError as e:
                print(f"WARNING: Could not parse template dsp_spec.json: {e}", file=sys.stderr)

    # ── Validate ──────────────────────────────────────────────────────────────
    errors = validate_spec(spec)
    if errors:
        for err in errors:
            print(f"ERROR: {err}", file=sys.stderr)
        sys.exit(1)
    if not template_dir.is_dir():
        print(f"ERROR: Template directory not found: {template_dir}", file=sys.stderr)
        sys.exit(1)

    # ── Render header ─────────────────────────────────────────────────────────
    header_content = render_header(spec, args.plugin_name)

    if args.dry_run:
        print("✓ DspSpec is valid")
        print(f"  Plugin type: {spec.get('plugin_type', 'effect')}")
        print(f"  Parameters:  {len(spec.get('parameters', []))}")
        print("  Would write:  Source/generated_config.h")
        sys.exit(0)

    # ── Write output ──────────────────────────────────────────────────────────
    source_dir = template_dir / "Source"
    source_dir.mkdir(parents=True, exist_ok=True)

    output_path = source_dir / "generated_config.h"
    output_path.write_text(header_content, encoding="utf-8")

    print(f"✓ Written: {output_path}")
    print(f"  Parameters injected: {len(spec.get('parameters', []))}")


if __name__ == "__main__":
    main()
